### ISSUE TITLE
Show Block Break Stage to Player

### ISSUE THREAD

**Issue by boxic** [MorkaZ/MorkazSk#10]
Hey! I'm having a problem showing block cracks on my server, here is my code:

```
on break:
	if event-block is stone:
		set {_block} to event-block
		if {blockdata::%location of event-block%} is not set:
			set {blockdata::%location of event-block%} to location of event-block
			set {blockdata::%location of event-block%::block} to stone
			set {blockdata::%location of event-block%::maxhealth} to 100
			set {blockdata::%location of event-block%::health} to 100
		if 10 < {blockdata::%location of event-block%::health}:
			remove 10 from {blockdata::%location of event-block%::health}
			cancel event
		else:
			set {blockdata::%location of event-block%::health} to 0
		set {_stage} to round ( 9 - ({blockdata::%location of event-block%::health} / ( {blockdata::%location of event-block%::maxhealth} / 9 ) ) )
		show block damage stage {_stage} at {_block} for all players
		send "%event-block% is now %{blockdata::%location of event-block%::health}% / %{blockdata::%location of event-block%::maxhealth}%"
```

when loading this skript, `show block damage stage {_stage} at {_block} for all players` pulls an error. I've tried a few variations of the effect, but I cannot seem to get it to work!

**Comment by MorkaZ** [comment]
Can you please post this error? I need to see what happened and where.

**Comment by boxic** [comment]
https://pastebin.com/iXPDM1Gd

**Comment by boxic** [comment]
It’s in there, ctrl+f

[15:28:10] [Server thread/ERROR]: [Skript] Can't understand this condition/effect: show block damage stage {_stage} at {_block} for all players (Mining.sk, line 15: show block damage stage {_stage} at {_block} for all players')

**Comment by boxic** [comment]
This is the same as I sent in my first post, so if I’m not understanding something please make it clear

**Comment by MorkaZ** [comment]
Do you have protocollib installed?

**Comment by boxic** [comment]
No, I did not

**Comment by MorkaZ** [comment]
It requires Protocollib. You have to install it to use packets features.
