### ISSUE TITLE
kupno

### ISSUE THREAD

**Issue by kijl** [MorkaZ/MorkazSk#11]
skoro jest opcja kupna pluginu MoxTokensDatabase to chciałbym się dowiedzieć jaka jest jego cena.

**Comment by MorkaZ** [comment]
Jesteśmy w trakcie tworzenia strony z naszymi pluginami.
Cały sklepik premium będzie kosztował 100 zł. Będzie on miał:
- Dwie waluty (jedna premium "tokeny", a druga do zdobycia w grze "talony") które są zgodne z EULĄ Mojangu
- Bardzo rozbudowane GUI (podobne do tego z pluginu Bosshop) gdzie tworzy się własne strony i bardzo zasadnie konfiguruje przyciski.
- Potwierdzenie kupna przedmiotu także w okienku (unikanie misclicków itd)
- Rozbudowana historia transakcji pod komendą
- Pełna możliwość nazewnictwa własnych komend w configu
- Możliwość ustawiania różnego typu promocji na wybrane waluty, oraz dodać obiekty w okienku które będą losowo wybierać przedmioty z sklepiku jako promocyjne w podanym zakresie w configu.
- Możliwość 2 baz danych - MySQL i SQLite (domyślna SQLite).
- Plugin ma także szereg komend administracyjnych oraz tych, którymi posługują się gracze.
Całość jest bardzo prosta w konfiguracji, jedynie czasochłonne jest ustawianie okienek.
Działanie sklepiku można zobaczyć na gc2.pl (tryb skyblock), jest tam ukazany jego potencjał.

**Comment by kijl** [comment]
Ok. To przelew mam zrobić z tego adresu https://www.paypal.me/Morkazoid i podać e-mail na który wyślesz pluginy tak?

**Comment by MorkaZ** [comment]
Jeżeli chciałbyś ten plugin już teraz to tak, możesz przelać. Proszę tylko wyślij jako "do znajomego" (email paypala to piter-909@tlen.pl jak coś), ponieważ paypal nie pobiera wtedy opłat. Myślę, że warto mieć taki plugin, zwłaszcza, jeżeli robisz serwer który ma mieć przychód. Taki sklepik na pewno bardziej zachęci do wydawania pieniędzy więc bardzo szybko się zwróci.  
Będzie trzeba zainstalować łącznie 2 pluginy - MocCore i MoxPremiumShop. MoxCore to biblioteka pluginów zaczynających się na "Mox".

**Comment by MorkaZ** [comment]
Jeżeli chciałbyś ten plugin już teraz to tak, możesz przelać. Proszę tylko wyślij jako "do znajomego" (email paypala to piter-909@tlen.pl jak coś), ponieważ paypal nie pobiera wtedy opłat. Myślę, że warto mieć taki plugin, zwłaszcza, jeżeli robisz serwer który ma mieć przychód. Taki sklepik na pewno bardziej zachęci do wydawania pieniędzy więc bardzo szybko się zwróci.
Będzie trzeba zainstalować łącznie 2 pluginy - MocCore i MoxPremiumShop. MoxCore to biblioteka pluginów zaczynających się na "Mox".

Jeżeli potrafisz pisać w Skript to najnowszy MorkazSk, którego będę niedługo wrzucał, ma do tego pluginu expressions - a dokładniej "tokens/talons of %player%/%string%". Będziesz mógł zrobić jakieś skrypty, które będą dodawały np. talony co 5 minut lub np. dodać szansę podczas kopania kamienia.

**Comment by kijl** [comment]
Pieniądze zostały przelane. Pluginy możesz wysłać na adres kg639306@gmail.com

**Comment by MorkaZ** [comment]
Hej, Przepraszam że tak późno piszę. Dopiero dzisiaj sprawdziłem paypal. Pluginy zaraz będą na mailu :)
