### ISSUE TITLE
brak pluginów

### ISSUE THREAD

**Issue by kijl** [MorkaZ/MorkazSk#12]
Niby wysłałeś a na e-mailu nie wiadomości od Ciebie

**Comment by MorkaZ** [comment]
![image](https://user-images.githubusercontent.com/4214815/59076805-30875600-88d8-11e9-9dbb-d79433bf5adb.png)
Sprawdź w spamie ewentualnie jeżeli email blokuje ci wiadomości z plikami tego typu to wyślę ci link do pobrania

**Comment by kijl** [comment]
Przeszukałem całą pocztę i nie znalazłem e-maila. Nawet za pomocą wyszukiwania wiadomości nic nie pomogło

**Comment by MorkaZ** [comment]
Wysłałem jeszcze raz na wcześniejszy i ten nowy email, sprawdź pocztę i napisz czy dostałeś.

**Comment by kijl** [comment]
Wszystko jest. Dzięki

**Comment by MorkaZ** [comment]
Gdyby coś nie działało w którymś z tych pluginów to pisz proszę na maila. Jest niby wszystko przetestowane i działa w praktyce na hubie ale w zależności od silnika może być różnie. Teoretycznie powinno wszystkie działać na wyższych wersjach ale gdyby coś było nie tak to daj znać.
