### ISSUE TITLE
on chunk enter event

### ISSUE THREAD

**Issue by LordiansOfTheGalaxy** [MorkaZ/MorkazSk#13]
![image](https://user-images.githubusercontent.com/50047020/59224160-62e5cb80-8bd6-11e9-97c9-5fc7620f3731.png)
Help me, this is not working.

**Comment by MorkaZ** [comment]
What exactly is not working? There is registered event-player in this event up from this bugfix. Try to download latest version.

**Comment by LordiansOfTheGalaxy** [comment]
I use latest version.

Piotr Osadnik <notifications@github.com>, 12 Haz 2019 Çar, 01:09 tarihinde
şunu yazdı:
