### ISSUE TITLE
Can't turn index from UUID to player

### ISSUE THREAD

**Issue by MdsCool** [MorkaZ/MorkazSk#14]
When using `set X to sorted Y from highest to lowest with format "@index: @value stuff"` for example, when you try to turn `@index` to something else, skript will throw an error.
What I mean is something like this `with format "%@index parsed as offline player%: @value stuff"` (index being a UUID)
I'm not sure if it even is meant to be possible or if this is a problem, but it'd be nice if if this can be fixed.

Error: https://hastebin.com/avivolacuk.cs
Code (if you need it): https://hastebin.com/weceticuda.sql

**Comment by MdsCool** [comment]
This isn't needed anymore, found a workaround

**Comment by MorkaZ** [comment]
You can not use @index and @value in skript's execution because this placeholders are not expressions.
