### ISSUE TITLE
brake stage reset

### ISSUE THREAD

**Issue by PoonsOfficial** [MorkaZ/MorkazSk#15]
I'm trying to set the break stage back to 0 (reset the animation) after `show block break stage 2 at event-block to player` but it will not clear. No errors either.

**Comment by Sops1510** [comment]
up on this?

**Comment by PoonsOfficial** [comment]
@Sops1510 I just deleted the block and re-placed it to get it to reset for me.

**Comment by LualtOfficial** [comment]
sorry for the necro-post but the breaking and re-placing doesnt work for me what code did you use?

**Comment by PnsDev** [comment]
> sorry for the necro-post but the breaking and re-placing doesnt work for me what code did you use?

I assume I did what I stated 2-3 years ago lol
