### ISSUE TITLE
disable glowing

### ISSUE THREAD

**Issue by Theyka** [MorkaZ/MorkazSk#17]
Hello when I try "make player glow with color "NONE" for players" it didn't work I using 1.15.2

**Comment by MorkaZ** [comment]
Do you have this plugin installed?
https://www.spigotmc.org/resources/api-glowapi.19422/

**Comment by Govindass** [comment]
I am having the same problem, I have GlowAPI, I used it with skript-mirror before your addon and GlowAPI itself has the same issue

using "NONE" does not remove glow, I must use invalid color to remove glow, like "anywordhere"

but with MorkazSK, invalid words do not work, thus no way to remove glow at all

**Comment by MorkaZ** [comment]
> I am having the same problem, I have GlowAPI, I used it with skript-mirror before your addon and GlowAPI itself has the same issue
> 
> using "NONE" does not remove glow, I must use invalid color to remove glow, like "anywordhere"
> 
> but with MorkazSK, invalid words do not work, thus no way to remove glow at all

Thanks for detailed information about this problem. I will try to fix it tomorrow by doing exactly what you have typed.

**Comment by Govindass** [comment]
> 
> 
> > I am having the same problem, I have GlowAPI, I used it with skript-mirror before your addon and GlowAPI itself has the same issue
> > using "NONE" does not remove glow, I must use invalid color to remove glow, like "anywordhere"
> > but with MorkazSK, invalid words do not work, thus no way to remove glow at all
> 
> Thanks for detailed information about this problem. I will try to fix it tomorrow by doing exactly what you have typed.
> 
> Invalid word will not work because my code checks if given text is in GlowApi.Color enum range:
> `if (ToolBox.enumContains(GlowAPI.Color.class, (color+"").toUpperCase())){ }`

thank you for quick response, I'll be happy to use your addon for GlowAPI as skript-mirror is slower

**Comment by MorkaZ** [comment]
> > > I am having the same problem, I have GlowAPI, I used it with skript-mirror before your addon and GlowAPI itself has the same issue
> > > using "NONE" does not remove glow, I must use invalid color to remove glow, like "anywordhere"
> > > but with MorkazSK, invalid words do not work, thus no way to remove glow at all
> > 
> > 
> > Thanks for detailed information about this problem. I will try to fix it tomorrow by doing exactly what you have typed.
> > Invalid word will not work because my code checks if given text is in GlowApi.Color enum range:
> > `if (ToolBox.enumContains(GlowAPI.Color.class, (color+"").toUpperCase())){ }`
> 
> thank you for quick response, I'll be happy to use your addon for GlowAPI as skript-mirror is slower

I will probably create my own function for this instead of using this api.

**Comment by PolsatGraniePL** [comment]
@Theyka , use 
`set glowing of player to false` for unglowing player
