### ISSUE TITLE
MakeEntityGlowWithColor feature doesn't work

### ISSUE THREAD

**Issue by TUCAOEVER** [MorkaZ/MorkazSk#18]
command /tx:
	trigger:
		make player glow with color "RED" for players

Doesn't work on 1.15.2 server. Using paper with glowapi and packetlistenerapi installed

glow color always white

**Comment by Govindass** [comment]
it's very sensitive to scoreboard / disguise systems, it works on my 1.12.2 server

**Comment by MorkaZ** [comment]
This feature is from GlowAPI, the problem is in this plugin. I will try to do my own api for glowing and I will introduce it to MorkazSk
