### ISSUE TITLE
Serialize Player's Inventory / Restore inventory from serialization

### ISSUE THREAD

**Issue by AsuDev2** [MorkaZ/MorkazSk#2]
A way to save a player's inventory in one variable instead of saving 36 slots to 36 different variables. 

Ex.

Set {inventory.%uuid of player%} to morkaz serialized contents of player's inventory
morkaz set [serialized] contents of player's inventory to {inventory.%uuid of player%}

It would be awesome if there was something like this as having 36 variables to save a player inventory is very annoying and takes up a bunch of space.

**Comment by MorkaZ** [comment]
I am working on implementing MoxData into MorkazSk.
It will be possible to use it in way what you have explained and save all multiple objects into one value.

Syntaxes will look like this:
```
set {_mox.data} to new mox data
add {_slot.item} with key {_slot.number} to {_mox.data}
remove value by|with key {_slot.number} from {_mox.data}
remove {_slot.item} from {_mox.data}
```

Also, it will be possible to generate and create mox data from single string (usefull for databases):
```
set {_mox.data.text} to "%{_mox.data}%" # or: string of {_mox.data}
set {_mox.data} to mox data of {_mox.data.text}
```

**Comment by MorkaZ** [comment]
I have updated MorkazSk and implemented MoxData.
All syntaxes can be found here: https://docs.skunity.com/syntax/search/mox
