### ISSUE TITLE
make entity glow not working

### ISSUE THREAD

**Issue by 520Pig520** [MorkaZ/MorkazSk#21]
You're changed this effect or is a bug ? Because Skript is returning a error "Can't understand this condition/effect: make loop-player glow with color "WHITE" for player"
`		loop all players:
				if {mode.control.%loop-player%} is "false":
					make loop-player glow with color "WHITE" for player`
I already tried use morkazsk before make, and nothing, return the same error.

**Comment by MorkaZ** [comment]
It requires external plugin: GlowAPI. Make sure it is installed and enabled also this feature depends fully on it so if API will not be working then this feature also.

**Comment by MorkaZ** [comment]
It requires external plugin: GlowAPI. Make sure it is installed and enabled also this feature depends fully on it so if API will not be working then this feature too.
