### ISSUE TITLE
wersja silnika

### ISSUE THREAD

**Issue by kijl** [MorkaZ/MorkazSk#3]
Witam.
Czy ten plugin będzie działał tylko na craftbukkicie?

**Comment by MorkaZ** [comment]
Ten plugin powinien działać na paper-spigot, spigot i bukkicie. Ogólnie na wszystkim co ma bukkit api.
Na czym chciałbyś, aby jeszcze działał? Z góry - sponge i bungeecord odpadają bo pod nie trzeba zrobić wszystko odrębnie.

**Comment by MorkaZ** [comment]
Jaki był błąd przy ładowaniu?
Jaki dokładnie paper spigot masz? Która wersja?

**Comment by MorkaZ** [comment]
Jaki był błąd przy ładowaniu pluginu? (sprawdz logi)

**Comment by kijl** [comment]
https://code.skript.pl/enekhuR8

**Comment by MorkaZ** [comment]
Dziękuję za logi.
Widocznie paper nie ma w sobie bibliotek Ansi (od kolorowego pisania np. w konsoli). Trochę dziwne bo np. spigot miał je od kiedy pamiętam. Mogliby je wrzucić, aby zwiększyć kompatybilność.
Dołączę te biblioteki w najnowszym buildzie MorkazSk, aby klasy istniały w razie, gdyby silnik ich nie miał.
Lada moment pojawi się nowa wersja MoxCore i MorkazSk. Po pobraniu ich i wrzuceniu do folderu plugins nie powinny występować już błędy.

**Comment by MorkaZ** [comment]
Nowa wersja już jest. Teraz wszystko powinno działać poprawnie. Pobierz nowe MorkazSk i MoxCore i sprawdź czy plugin się ładuje.

**Comment by MorkaZ** [comment]
Czy problem dalej występuje?

**Comment by kijl** [comment]
Problemu już nie ma
