### ISSUE TITLE
Glow color code "NONE" does not working

### ISSUE THREAD

**Issue by OverBrave** [MorkaZ/MorkazSk#30]
**Describe the problem**
Even if we set the color code to "NONE", it continues to glow in "White".
But on SkriptHUB, "NONE" states that it has turned off the glow.

GlowAPI 1.4.20-SNAPSHOT
MorkazSK 1.2
Skript 2.6-beta3
AirPlane Purpur #44 Build

**Comment by MorkaZ** [comment]
It is not MorkazSk issue.

**Comment by OverBrave** [comment]
> It is not MorkazSk issue.

Its cause of GlowAPI?

**Comment by MorkaZ** [comment]
> > It is not MorkazSk issue.
> 
> Its cause of GlowAPI?

Yes
