### ISSUE TITLE
Block break stage 

### ISSUE THREAD

**Issue by Hykonic** [MorkaZ/MorkazSk#31]
I have an issue where the block break stage wont reset after i set it to 0.I am making a custom block breaking system using your addon.Im showing the damage from 1-9 then when it hits the stage 9 i set it to 0 but it doesnt clear it,the damage stays 9.

**Comment by MorkaZ** [comment]
Break stage is animation. It works like any particle in minecraft and it has long duration. As far as I know it is impossible to despawn it.
