### ISSUE TITLE
Cannot sort timespans

### ISSUE THREAD

**Issue by SadShikawa** [MorkaZ/MorkazSk#33]
Not sure if this is a bug report or a feature request, but still. When I try to sort a variable with only timespans in it, if there's only 1 variable, it will just throw it out, but if there's more than 1 timespan, it will throw an internal error: https://www.toptal.com/developers/hastebin/oheculodex.md
my code: https://www.toptal.com/developers/hastebin/odigukekul.sql
is there any way to sort timespans?

**Comment by MorkaZ** [comment]
It sorts only number values using some java library and creates custom output on sorted list.

**Comment by MorkaZ** [comment]
To sort dates you first should transform date to unix timestamp which is long number, sort it and then change this number back to date.
