### ISSUE TITLE
Problem with glow

### ISSUE THREAD

**Issue by Martin2000s** [MorkaZ/MorkazSk#34]
Hello, 
I can't really get the glow to work, I even used your example from skripthub and even that one doesn't work. Skript doesn't understand the condition. I'm using ver 1.3 but I tried with 1.2 too with the same result.

With regards,
Martin

**Comment by MorkaZ** [comment]
It requires GlowAPI plugin.

**Comment by Martin2000s** [comment]
Oh I get it now. I mean I had it but I'm on 1.18.2 and the plugin hasn't been updated to it yet. Thanks for your help!
