### ISSUE TITLE
Glowing / Glowing Color

### ISSUE THREAD

**Issue by AsuDev2** [MorkaZ/MorkazSk#4]
Can you make a feature where you can make an entity glow (not just players, all entities)? Also make a way to turn off the glow. And most importantly, a way to specify the color of the glow. Example syntax's:

Make %entity% glow [%string%] # Make the player glow. The %string% would be a color. If color is not specified, make the color white.

Make %entity% stop glowing # Make the entity stop glowing

SharpSK's features for glow really suck and don't work well so a new add on with this support would be awesome.

**Comment by MorkaZ** [comment]
I may be incorrect but entity glowing is potion effect and should be able to be applied using "apply potion to entity" effect

**Comment by MorkaZ** [comment]
I may be incorrect but entity glowing is potion effect and should be able to be applied using "apply potion to entity" effect. If it is true then there is no point in creating effect like you suggested.

**Comment by AsuDev2** [comment]
I believe you can only apply potion effects to living entities. So I believe you cannot apply them to dropped items, item frames, etc.

**Comment by MorkaZ** [comment]
Thanks. Then I will add it to MorkazSk in near future.
Syntax should look like this:
`make %entities% glow with color %color% for %players%`

**Comment by MorkaZ** [comment]
I have checked docs and asked community if Entity (not living) is possible to have colored glowing effect. It seems that it is impossible, it can be done only with living entities. I may be incorrect but with my knowledge it is not possible to do. If you (or someone) will find a way or will show how to do it, then I will try to create effect like you suggested.

**Comment by MorkaZ** [comment]
You are right. I have added it into MorkazSk. It will be updated soon :)!

**Comment by MorkaZ** [comment]
Requested feature has been added in new update.
