### ISSUE TITLE
Unknown error cause

### ISSUE THREAD

**Issue by Hexivoid** [MorkaZ/MorkazSk#5]
I just found Morkaz today and would like to use it for its ability to sort lists/arrays. Can you please specify if this is an error on my end or something with MorkazSk? Thanks!

Using Skript 2.3.5 (latest)
Using Spigot 1.12.2
Using multiple addons, can provide a list

![morkazerror1](https://user-images.githubusercontent.com/20330597/52916221-b42a2200-32aa-11e9-8529-a7aa04c3d5e8.PNG)
![morkazerror2](https://user-images.githubusercontent.com/20330597/52916222-b42a2200-32aa-11e9-922f-f4100142f104.PNG)

**Comment by MorkaZ** [comment]
You have to install `MoxCore` to use MoxData features.

**Comment by MorkaZ** [comment]
You have to install `MoxCore` plugin from [there](https://github.com/GC2Network/MoxCore/releases) to use MoxData features.
This error says that your server does not have installed MoxLibrary classes which are in MoxCore.
I do not understand why MorkazSk started loading MoxCore optional features when MoxCore was not enabled. I have to take look on this.

**Comment by Hexivoid** [comment]
Thank you very much! Is there a manual option to disable MoxCore? I sure don't see it in the config if there is one. I resorted to MorkazSk when I could not figure out how to use Skript's sort effects and expressions, but it turns out sorting is currently broken in Skript. You can take a look at the report [here](https://github.com/SkriptLang/Skript/issues/1904) if you think Skript might be affecting MorkazSk loading.

**Comment by MorkaZ** [comment]
> Here is manual:
> https://github.com/MorkaZ/MorkazSk/wiki/Mox-Data-tutorial
>

**Comment by MorkaZ** [comment]
Sorry for little confusion. I had no time and everything was read fast and typed quickly.

There is no way to disable loading of MoxData type if MoxCore is installed on your server.
Can you post list of your plugins? I was trying to reproduce this error but without any effect. Everything is working corectly on my test server.

**Comment by MorkaZ** [comment]
Can you also check logs if there was any error with enabling MoxCore? It may be the cause of this issue.

**Comment by Hexivoid** [comment]
Have Discord? I'd rather not post such lists here!

**Comment by MorkaZ** [comment]
Found problem cause:  
When there was no optional plugins then special array was empty and Skript was loading (I do not know why..) all subpackages of `optional` MorkazSk plugin's package where were all other plugins features.
Thank you so much for reporting. Problem is fixed.
