### ISSUE TITLE
on chunk enter

### ISSUE THREAD

**Issue by BirdyCanFly** [MorkaZ/MorkazSk#6]
Hey, skript tells me that the event "On chunk enter/leave" doesn' t have a player. 
But when i look on https://skripthub.net/docs/ 
I see that you set an example with an player. Is this a bug or a wrong example on the site?

**Comment by BirdyCanFly** [comment]
And is there a reason why i should use on chunk enter instead of on any movement? 
does it reduce lagg?

**Comment by MorkaZ** [comment]
Thank you for reporting. Player value was not registered. It should be fixed in latest release.
It is much more efficient.
