### ISSUE TITLE
MoxTokensDatabase

### ISSUE THREAD

**Issue by kijl** [MorkaZ/MorkazSk#9]
Witam.
Chciałbym z tego pluginu użyć waluty lecz coś nie działa.
Z kodu wyczytałem, że jest potrzebny plugin MoxTokensDatabase, ale nie mogę go nigdzie znaleźć. 
@MorkaZ dlaczego nie odpisujesz?
#ref

**Comment by MorkaZ** [comment]
Plugin MoxTokensDatabase nie jest open source.
